# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeCurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.SmallIntegerField()),
                ('semestre', models.CharField(max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='curso',
            name='Matriz_Curricular',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='carga_horaria',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='disciplina',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='carga_horaria',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='prativa',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disciplina',
            name='teoria',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='apelido',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curso',
            name='carga_horaria',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='sigla',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='tipo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(max_length=240),
        ),
        migrations.AddField(
            model_name='gradecurricular',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Curso'),
        ),
    ]
