# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 18:09
from __future__ import unicode_literals

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171116_1559'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', core.models.UsuarioManager()),
            ],
        ),
    ]
