# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 23:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171125_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disciplina',
            old_name='prativa',
            new_name='pratica',
        ),
    ]
