# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171125_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='pratica',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='teoria',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
    ]
