# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 00:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171125_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.SmallIntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Curso')),
                ('gradecurricular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.GradeCurricular')),
            ],
        ),
    ]
