# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_professor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
