# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20171125_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradecurricular',
            name='ano',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='gradecurricular',
            name='semestre',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='numero',
            field=models.SmallIntegerField(unique=True),
        ),
    ]
