# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_disciplina_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='email',
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.CharField(default='example@host.com', max_length=100),
        ),
    ]
