# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_disciplinaofertada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradecurricular',
            name='ano',
            field=models.SmallIntegerField(),
        ),
    ]
