# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20171126_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinaofertada',
            name='ano',
            field=models.SmallIntegerField(),
        ),
    ]
