# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20171126_0118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(max_length=15)),
                ('ano', models.SmallIntegerField()),
                ('semestre', models.CharField(max_length=1)),
                ('disciplinaofertada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DisciplinaOfertada')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Professor')),
            ],
        ),
    ]
